# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development: &DEV
  adapter: postgresql
  encoding: unicode
  database: simulator_development
  pool: 5
  username: simulator
  password: simulator
  # adapter: mysql2
  # encoding: utf8
  # reconnect: false
  # database: simulator_dev
  # pool: 5
  # username: root
  # password: root
  # socket: /var/run/mysqld/mysqld.sock

test: &TEST
  <<: *DEV
  database: simulator_test
  username: eduardo
  password: edu211290

production:
  adapter: postgresql
  encoding: unicode
  database: simulator_production
  pool: 5
  username: postgres
  password:
